### PR TITLE
Added spaninsh translation, it is a generic translation

### PR DESCRIPTION
**Pull request by julian-alarcon**
Added Spanish translation. It works for any country (Spain, Latin America, etc) as it is really generic.

### CODE REVIEW

**Comment by Sukigu** [comment]
Sorry for taking so long to reply, but thanks for your contribution!

Please review the latest changes to the English file: some text has been updated (it was mostly English grammar improvements; you should only need to update the description) and some string keys were changed. Also, please fix the missing accent in "busqueda."

**Review by julian-alarcon — COMMENTED** [review]
Hi! Can you check again this pull request to add new language? Thank you!

**Comment by Sukigu** [comment]
Hey, thanks again! :)

However, do you think `Buscar en Google la imagen` sounds more natural than your previous `Buscar imagen en Google`? I changed it in English because it matches Firefox's already existing string when you highlight some text (`Search Google for <x>`), but I left it how it was in my native Portuguese (`Pesquisar imagem no Google`).

**Comment by julian-alarcon** [comment]
Hi @Sukigu I got it! I just changed it. You are right, sound more natural, but sometimes people in some projects prefer the strict order.
BTW I like your style better!

**Comment by Sukigu** [comment]
Thanks, it'll be on the next version!

**Pull request merged**
